version: 0.2

env:
  parameter-store:
    # Parameter Store의 이름을 왼쪽 / buildspec에서 사용할 변수명을 오른쪽에 둡니다.
    S3_BUCKET: "/kmj-web/prod/S3_BUCKET"
    CLOUDFRONT_DISTRIBUTION_ID: "/kmj-web/prod/CLOUDFRONT_ID"
    REACT_APP_API_URL: "/kmj-web/prod/REACT_APP_API_URL"

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
#      - echo "API URL is set to: $REACT_APP_API_URL"
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
#      - echo "Uploading to S3 bucket: $S3_BUCKET"
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete
#      - echo "Invalidating CloudFront cache: $CLOUDFRONT_DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" || echo "CloudFront invalidation skipped"

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'