version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building React application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3...
      - aws s3 sync build/ s3://${S3_BUCKET}/ --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*" || echo "CloudFront invalidation skipped"

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'